// Generated by ReScript, PLEASE EDIT WITH CARE


import { render, screen } from '@testing-library/react';
import App from './App.res';

test('renders learn react link', () => {
  render(<App />);
  const linkElement = screen.getByText(/learn react/i);
  expect(linkElement).toBeInTheDocument();
});
;

export {
  
}
/*  Not a pure module */
