// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReactDom from "react-dom";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import ReportWebVitals from "./reportWebVitals";
import * as App$RescriptReactHelloWorld from "./App.bs.js";

import './index.css';
;

var reportWebVitals = ReportWebVitals;

var rootQuery = document.querySelector("#root");

if (!(rootQuery == null)) {
  ReactDom.render(React.createElement(App$RescriptReactHelloWorld.make, {}), rootQuery);
}

Curry._1(reportWebVitals, undefined);

var rootQuery$1 = (rootQuery == null) ? undefined : Caml_option.some(rootQuery);

export {
  reportWebVitals ,
  rootQuery$1 as rootQuery,
  
}
/*  Not a pure module */
